name: Dev Docker Build
run-name: "Dev build repository: ${{ github.ref_name }} #${{ github.run_number }}"

on:
  workflow_dispatch:
    inputs:
      custom-image-name:
        description: 'Image name. If empty, use repository name'
        required: false
        default: ''
      tags:
        description: 'Tags'
        required: false
        type: string
        default: ''
      dry-run:
        description: 'Dry run'
        required: false
        type: boolean
        default: false
  push:
    branches:
      - '**'
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'CODE-OF-CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      - 'README.md'
      - 'SECURITY.md'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'CODE-OF-CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      - 'README.md'
      - 'SECURITY.md'
permissions:
  contents: read

env:
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  docker-build:
    name: "Build and Publish Docker Image"
    permissions:
      packages: write
      contents: read
    outputs:
      metadata: "${{ steps.metadata.outputs.result }}"
      tags: "${{ steps.prepare_tags.outputs.tags }}"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: "Create name"
        uses: netcracker/qubership-workflow-hub/actions/metadata-action@b575bad3a0959c4e883bc34f9d055ff07fde2dbd # v1.0.7
        id: metadata

      - name: "Prepare tags"
        id: prepare_tags
        run: |
          BASE_TAG="${{ steps.metadata.outputs.result }}"
          EXTRA_TAG="${{ github.event.inputs.tags }}"
          if [ -n "$EXTRA_TAG" ]; then
            TAGS="${BASE_TAG}, ${EXTRA_TAG}"
          else
            TAGS="${BASE_TAG}"
          fi
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT

      - name: "Summary step"
        run: |
          echo "**Metadata:** ${{ steps.metadata.outputs.result }}" >> $GITHUB_STEP_SUMMARY
          echo "**Tags:** ${{ steps.prepare_tags.outputs.tags }}" >> $GITHUB_STEP_SUMMARY

      - name: "Build and Publish Docker Image"
        uses: netcracker/qubership-workflow-hub/actions/docker-action@b575bad3a0959c4e883bc34f9d055ff07fde2dbd #v1.0.7
        with:
          custom-image-name: ${{ github.event.inputs.custom-image-name || '' }}
          platforms: ${{ env.PLATFORMS }}
          checkout: "false"
          tags: ${{ steps.prepare_tags.outputs.tags }}
          dry-run: ${{ github.event.inputs.dry-run || 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
